version: 2.1

orbs:
  node: circleci/node@4.7

jobs:

  lint-commit:
    working_directory: ~/commitlint_example
    docker:   
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npx commitlint

  build: 
    working_directory: ~/commitlint_example # Virtual folder in docker
    docker: 
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm start

  test:
    working_directory: ~/commitlint_example
    docker: 
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm test
      

workflows:
  lint-build-test:
    jobs:
      - lint-commit
      - build:
          requires:
            - lint-commit
      - test:
          requires:
            - build