version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0
  yamllint: freighthub/yamllint@1.0.0
  commitlint: conventional-changelog/commitlint@1.0.0
  changelog: ory/changelog@0.1.10

defaults: &defaults
  working_directory: ~/commitlint_example # Virtual folder in docker
  # docker:
  #   - image: cimg/node:15.0.1

jobs:

  setup: &setup
    # <<: *defaults
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - persist_to_workspace:
        root: ~/commitlint_example
        paths:
          - .

  build: &build
    # <<: *defaults
    steps:
      - attach_workspace:
          at: ~/commitlint_example
      - run: npm start

  test: &test
    # <<: *defaults
    steps:
      - attach_workspace:
          at: ~/commitlint_example
      - run: npm test      

workflows:
  lint-build-test-release:
    jobs:
      - setup

      - yamllint/yamllint:
          requires:
            - setup
          files: ./test/docker.yml
          gitToken: ${GITHUB_TOKEN}

      - commitlint/lint:
          requires:
            - setup
          # max-count: 5
          # target-branch: develop
          target-branch: master

      - build:
          requires:
            - yamllint/yamllint
            - commitlint/lint

      - test:
          requires:
            - build

      - changelog/generate:
          context: GITHUB_CREDS
          gitemail: $GITHUB_EMAIL
          gitusername: $GITHUB_USERNAME
          requires:
            - test
          filters:
            branches:
              only: 
                - master

      - gh/release:
          notes-file: CHANGELOG.md
          tag: 1.0.7
          title: Change commit-lint, yaml-lint, release note NPM/NPX to CIRCLECI ORBS + CHANGELOG
          requires: 
            - changelog/generate
          context: 
            - GITHUB_CREDS
          filters:
            branches:
              only: 
                - master
