version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0
  commitlint: conventional-changelog/commitlint@1.0

jobs:

  lint-yaml:  
    working_directory: ~/commitlint_example
    docker:
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run yaml-lint

  # lint-commit:
  #   working_directory: ~/commitlint_example
  #   steps:
  #     - checkout
  #     - commitlint/lint

  build: 
    working_directory: ~/commitlint_example # Virtual folder in docker
    docker: 
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm start

  test:
    working_directory: ~/commitlint_example
    docker: 
      - image: "circleci/node:16.10"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm test      

workflows:
  lint-build-test-release:
    jobs:
      - lint-yaml
      - commitlint/lint
      - build:
          requires:
            - lint-yaml
      - test:
          requires:
            - build
      - gh/release:
          notes-file: changelog.md
          tag: 1.0.0
          title: The initial release
          requires: 
            - test
          context: 
            - GITHUB_CREDS
          filters:
            branches:
              only: 
                - master