version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0

defaults: &defaults
  working_directory: ~/commitlint_example # Virtual folder in docker
  docker:
    - image: cimg/node:15.0.1
  steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - persist_to_workspace:
      root: . 
      paths:
        - '*'

jobs:

  lint-yaml: &lint-yaml
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: npm run yaml-lint

  lint-commit: &lint-commit
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Define environment variable with latest commit's message
          command:  |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: Lint commit message here
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  build: &build
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: npm start

  test: &test
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: npm test      

workflows:
  lint-build-test-release:
    jobs:
      - lint-yaml
      - lint-commit
      - build:
          requires:
            - lint-yaml
            - lint-commit
      - test:
          requires:
            - build
      # - gh/release:
      #     notes-file: changelog.md
      #     tag: 1.0.0
      #     title: The initial release
      #     requires: 
      #       - test
      #     context: 
      #       - GITHUB_CREDS
      #     filters:
      #       branches:
      #         only: 
      #           - master