version: 2.1

orbs:
  node: circleci/node@4.7
  gh: circleci/github-cli@1.0
  yamllint: freighthub/yamllint@1.0.0

defaults: &defaults
  working_directory: ~/commitlint_example # Virtual folder in docker
  docker:
    - image: cimg/node:15.0.1

jobs:

  setup: &setup
    <<: *defaults
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - persist_to_workspace:
        root: ~/commitlint_example
        paths:
          - .

  # lint-yaml: &lint-yaml
  #   <<: *defaults
  #   steps:
  #     # - checkout
  #     - attach_workspace:
  #         at: ~/commitlint_example
  #     - run: npm run yaml-lint

  lint-commit: &lint-commit
    <<: *defaults
    steps:
      # - checkout
      - attach_workspace:
          at: ~/commitlint_example
      - run: 
          name: Define environment variable with latest commit's message
          command:  |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run: 
          name: Lint commit message here
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  build: &build
    <<: *defaults
    steps:
      # - checkout
      - attach_workspace:
          at: ~/commitlint_example
      - run: npm start

  test: &test
    <<: *defaults
    steps:
      # - checkout
      - attach_workspace:
          at: ~/commitlint_example
      - run: npm test      
  
  # changelog-create: &changelog-create
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: ~/commitlint_example
  #     - run: npm run release

workflows:
  lint-build-test-release:
    jobs:
      - setup
      - yamllint/yamllint:
          requires:
            - setup
          files: ../test/docker.yml
          gitToken: ${GITHUB_TOKEN}
      - lint-commit:
          requires:
            - setup
      - build:
          requires:
            - yamllint/yamllint
            - lint-commit
      - test:
          requires:
            - build
      # - changelog-create:
      #     filters:
      #       branches:
      #         only: 
      #           - master
      #     requires:
      #       - test
      # - gh/release:
      #     notes-file: changelog.md
      #     tag: 1.0.1
      #     title: Added commit-lint, yaml-lint & auto-created release note
      #     requires: 
      #       - test
      #     context: 
      #       - GITHUB_CREDS
      #     filters:
      #       branches:
      #         only: 
      #           - master
